### ISSUE TITLE
Applied patch, it partially worked but I want to revert it.

### ISSUE THREAD

**Issue by JawayWu** [flamewave000/df-fvtt-enhancement-suite#1]
Hi,
I have my foundry server installed on a raspberry pi. I followed the Linux installation instructions, however when I edit my world I do not see the background video option. That is the main reason I wanted to try installing the patch.
However, my modules/packages are now being alphabetically sorted, and I actually would like to revert that. How can I do so? Thank you.

**Comment by flamewave000** [comment]
Animated background script should be working if it was installed correctly. I'm currently using it in my own 0.8.9 server without issue.

If you want to disable the scripts, you can open this file:
`<foundry_installation>/resources/app/templates/views/layouts/main.hbs`

At the bottom of the file you'll find the following:

```hbs
<body class="{{ bodyClass }}" style="{{ bodyStyle }}">
    {{{body}}}
    {{#if watermark}}
    <p class="watermark">{{watermark}}</p>
    {{/if}}
<script defer src="scripts/anim-bg.js"></script>
<script defer src="scripts/module-sort.js"></script>
<script defer src="scripts/world-config.js"></script>
</body>
</html>
```

- `scripts/anim-bg.js` is the script that animates the login page.
- `scripts/module-sort.js` is what sorts the modules.
- `scripts/world-config.js` is what modifies the World Config dialog to allow you to configure the animated background for a world.

Simply remove any of these lines and save the file, then restart your server. You don't need to bother finding and deleting the script files themselves since they'll just disappear the next time you update Foundry.
